useTabs = true
singleQuote = false
trailingComma = "all"
printWidth = 120
plugins = ["prettier-plugin-svelte", "prettier-plugin-tailwindcss"]

[[overrides]]
files = "*.svelte"

[overrides.options]
parser = "svelte"
